name: Build QieMedia Dependencies 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - uses: microsoft/setup-msbuild@v3
    - name: Build
      shell: cmd
      run:  |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        onekey-build-qiemedia.cmd
    - uses: actions/upload-artifact@v7
      with:
        name: QieMedia.Packages
        path: Output\installed
